- test/.eslintrc.json
- test/api/request.spec.js
use expectAsync to expect promise fails
> Better async test

- CHANGELOG.md
- src/checkFileIsReady.ts
- src/checkFileIsUploadedFromUrl.ts
- src/defaultSettings.ts
- src/fileFrom/UploadFrom.ts
- src/fileFrom/UploadFromUrl.ts
- src/types.ts
> Add `pollingTimeoutMilliseconds` to `SettingsInterface`

- README.md
- test/_helpers.ts
because dev test doesn't have sense
> test: run test with production env on default

- test/jasmine.config.json
stop execution on failure and run tests in random order
> test: update jasmine config

- .travis.yml
> test: don't run test on node with version 8

- src/uploadFile/uploadFromUrl.ts
Prepare `uplaodFromUrl` for integration with push strategy
> refactor(uploadFromUrl): use promise chain for creating UploadcareFile

- src/tools/race.ts
- test/tools/race.test.ts
I found better names for race function.
> refactor(race): rename `callback` to `stopRace`

- src/uploadFile/events.ts
- test/tools/events.test.ts
Simple event-emitter for next usage in sockets
- add some test cases
> feat: add strong typed event emitter

- src/tools/poll.ts
- test/tools/poll.test.ts
Removes timeout stuff in uploadFromUrl
> fix: remove timeout in upload from url function

- package-lock.json
- package.json
- src/defaultSettings.ts
- src/tools/poll.ts
- src/tools/sockets.browser.ts
- src/tools/sockets.node.ts
- src/types.ts
- src/uploadFile/pollStrategy.ts
- src/uploadFile/pushStrategy.ts
- src/uploadFile/pusher.ts
- src/uploadFile/uploadFromUrl.ts
- test/tools/poll.test.ts
- test/uploadFile/fileFromUrl.test.ts
> feat: implement push strategy with sockets for upload from url

- src/uploadFile/pushStrategy.ts
- src/uploadFile/pusher.ts
added deferred disconnect for push strategy
> feat: add deferred disconnect for push strategy

- README.md
> docs(readme): update examples in readme

- .github/workflows/shipjs-manual-prepare.yml
- .github/workflows/shipjs-schedule-prepare.yml
- ship.config.js
Update shipjs config for [0.17 version](https://github.com/algolia/shipjs/releases/tag/v0.17.0)
> chore: update shipjs config

- package-lock.json
> chore(deps): fix vulnerabilities

- src/uploadFile/uploadMultipart.ts
use browser filename if option is not passed
> fix(multipart): use browser filename if option is not passed

- src/api/multipartStart.ts
- src/defaultSettings.ts
- src/types.ts
- src/uploadFile/index.ts
- src/uploadFile/uploadMultipart.ts
- src/uploadFileGroup/index.ts
use browser contentType if option is not passed
> fix(multipart): use browser contentType if option is not passed

- src/api/multipartUpload.ts
- src/uploadFile/uploadMultipart.ts
- test/api/multipartUpload.test.ts
implement progress for multipart node uploads
> fix: implement progress for multipart node uploads

- src/defaultSettings.ts
- src/tools/retry.ts
- src/tools/retryIfThrottled.ts
- src/types.ts
- src/uploadFile/uploadMultipart.ts
- test/tools/retry.test.ts
return multipartMaxAttempts parameter with retrying for failed multiparts uploads
> fix(multipart): implement retry for part uploading

- test/_fixtureFactory.ts
Previous project has been deleted so I changed uuid and public keys everywhere
> test: fix integration tests

- AUTHORS.txt
> chore: update email in AUTHORS.txt

- .github/workflows/shipjs-trigger.yml
- ship.config.js
setup shipjs and GHA for alpha releases from alpha branch
> chore: setup alpha releases

- .github/renovate.json
- package-lock.json
- package.json
- ship.config.mjs
> chore: move shipjs to esm

- CHANGELOG.md
- package-lock.json
- package.json
- src/uploadFile/index.ts
- src/version.ts
Passing specific parameters for URL file source into `uploadFile` common method
> From url duplicates

- packages/upload-client/README.md
> Add link to File metadata docs

- packages/api-client-utils/package.json
- packages/rest-client/package.json
- packages/rest-client/src/api/addons/addonExecutionStatus.test.ts
- packages/rest-client/src/api/conversion/documentConversionJobStatus.test.ts
- packages/upload-client/package.json
Post-fix after https://github.com/uploadcare/uploadcare-js-api-clients/pull/437
> Add react-native export field

- packages/upload-client/README.md
- packages/upload-client/src/index.ts
- packages/upload-client/src/tools/Queue.ts
- packages/upload-client/src/uploadFile/uploadFile.ts
- packages/upload-client/test/tools/queue.test.ts
> feat(upload-client): add `Queue` helper to make queued uploads

- packages/rest-client/src/api/conversion/conversionInfo.test.ts
- packages/rest-client/src/api/conversion/conversionInfo.ts
- packages/rest-client/src/index.ts
https://uploadcare.com/api-refs/rest-api/v0.7.0/#tag/Conversion/operation/documentConvertInfo
> feat(rest-client): add Document Info endpoint
